"""Manages this package's own daily-driver install as a global `uv tool` — decoupled from any
consumer repo's dependency groups. Nested under the `repo_tasks` collection name (invoke
dashifies that to `repo-tasks` on the CLI, same as `dev_env` -> `dev-env`), so `update`/`status`/
`version`/`stamp` can never collide with a consuming project's own local task names.

`--with-executables-from invoke` is the load-bearing flag in every install command here: `uv tool
install` does not expose a dependency's own console scripts by default (confirmed hands-on against
a real `uv 0.11.19` — a throwaway package depending on `invoke` only got its own entry point linked
into the tool bin dir, not `inv`/`invoke` — the same opt-in pipx historically required via
`--include-deps`). Without it, `uv tool install repo-tasks` would install fine but produce no
`inv` on PATH at all."""

import re
from importlib.metadata import version as _installed_version
from pathlib import Path

from invoke import task

_REPO_URL = "https://github.com/TheodoreAD/repo-tasks"
_STAMP_PATH = Path("bootstrap-repo-tasks.sh")
_INSTALL_CMD = "uv tool install --force --with-executables-from invoke"

_STAMP_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

# Regenerated by `inv configure` — do not hand-edit. Installs the repo-tasks version this repo
# was last configured against. For CI and reproducibility archaeology only: a human working
# locally runs `inv repo-tasks.update` instead, which moves the shared *global* install forward.
# Re-running this script by habit would silently reinstall the global tool to whatever version
# *this* repo last pinned, yanking it out from under any other repo just being worked on.

command -v uv >/dev/null 2>&1 || {{
  echo "uv not found on PATH — install uv first" >&2
  exit 1
}}
{install_cmd} 'repo-tasks @ git+{repo_url}@v{pinned_version}'
"""


def _latest_tag(c) -> str | None:
    """The newest `vX.Y.Z` tag on the upstream repo, or None if it has no tags yet (repo-tasks
    itself, pre-first-release, is exactly this case today)."""
    result = c.run(f"git ls-remote --tags --refs --sort=-v:refname {_REPO_URL} 'v*'", hide=True, warn=True)
    if not result.ok or not result.stdout.strip():
        return None
    first_ref = result.stdout.strip().splitlines()[0]
    return first_ref.rsplit("refs/tags/", 1)[-1]


def _stamped_version() -> str | None:
    """The version pinned in this repo's own bootstrap-repo-tasks.sh, or None if it hasn't been
    stamped yet (run `inv configure`)."""
    if not _STAMP_PATH.exists():
        return None
    match = re.search(r"repo-tasks @ git\+[^@]+@v([^']+)'", _STAMP_PATH.read_text())
    return match.group(1) if match else None


@task
def update(c):
    """Move the global daily-driver repo-tasks uv tool install forward to the latest tagged
    release (falls back to the default branch with a warning if no release has been tagged
    yet)."""
    tag = _latest_tag(c)
    if tag:
        target = f"repo-tasks @ git+{_REPO_URL}@{tag}"
    else:
        target = f"repo-tasks @ git+{_REPO_URL}"
        print("[repo-tasks.update] no tagged release found yet — installing from the default branch")
    c.run(f"{_INSTALL_CMD} '{target}'", echo=True)


@task
def status(c):
    """Compare the globally-installed repo-tasks version against what this repo was last
    `configure`d against — drift detection, read-only."""
    installed = _installed_version("repo-tasks")
    expected = _stamped_version()
    if expected is None:
        print(
            f"[repo-tasks.status] installed: {installed}; this repo has no stamped "
            "bootstrap-repo-tasks.sh yet (run `inv configure`)"
        )
        return
    if installed == expected:
        print(f"[repo-tasks.status] up to date — installed {installed}, repo expects {expected}")
    else:
        print(
            f"[repo-tasks.status] drift — installed {installed}, repo expects {expected}. "
            "Run `inv repo-tasks.update` to move the global install forward, or `inv configure` "
            "to re-pin this repo to what's currently installed."
        )


@task
def version(c):
    """Print the repo-tasks version currently active (whatever `inv` process is executing this,
    typically the global daily-driver install)."""
    print(_installed_version("repo-tasks"))


@task
def stamp(c):
    """Regenerate bootstrap-repo-tasks.sh, pinning the repo-tasks version active right now. Runs
    as part of `inv configure` — see the generated script's own header for why a human shouldn't
    run it directly."""
    installed = _installed_version("repo-tasks")
    script = _STAMP_TEMPLATE.format(install_cmd=_INSTALL_CMD, repo_url=_REPO_URL, pinned_version=installed)
    _STAMP_PATH.write_text(script)
    _STAMP_PATH.chmod(_STAMP_PATH.stat().st_mode | 0o111)
    print(f"[repo-tasks.stamp] wrote {_STAMP_PATH}, pinned to v{installed}")
