"""Manages this package's own daily-driver install as a global `uv tool` — decoupled from any
consumer repo's dependency groups. Nested under the `repo_tasks` collection name (invoke
dashifies that to `repo-tasks` on the CLI, same as `dev_env` -> `dev-env`), so `update`/`status`/
`version`/`stamp` can never collide with a consuming project's own local task names.

`--with-executables-from invoke` is the load-bearing flag in every install command here: `uv tool
install` does not expose a dependency's own console scripts by default (confirmed hands-on against
a real `uv 0.11.19` — a throwaway package depending on `invoke` only got its own entry point linked
into the tool bin dir, not `inv`/`invoke` — the same opt-in pipx historically required via
`--include-deps`). Without it, `uv tool install repo-tasks` would install fine but produce no
`inv` on PATH at all."""

import re
from importlib.metadata import version as _installed_version
from pathlib import Path

from invoke import Context, task

from .requirements import NETWORK, requires

_REPO_URL = "https://github.com/TheodoreAD/repo-tasks"
_STAMP_PATH = Path("bootstrap-repo-tasks.sh")
# No `--python`, deliberately — `uv tool install` with no explicit request derives one from this
# package's own `requires-python`. Measured on uv 0.11.19 against the stamped git-URL shape:
# "Using Python request `>=3.11` from `requires-python` metadata", then the newest managed install
# satisfying it. A machine states its own choice through `UV_PYTHON` (this one exports 3.14, from
# power-user-linux-setup's `[packages.uv-env]`) or a *global* `.python-version`; a local one is
# ignored for tool installs. Pinning a version into the template would take the one shape that is
# wrong for an artifact every consumer regenerates: an explicit request *overrides* `requires-python`
# rather than narrowing it, and installed a `>=3.9,<3.10` probe package onto 3.14 with no warning.
_INSTALL_CMD = "uv tool install --force --with-executables-from invoke"
# Reading the global install's version, which `importlib.metadata` structurally cannot do: it can
# only answer for the interpreter running it. No new dependency — `update` already shells out to
# `uv tool install`, and this module exists to manage a uv tool.
_TOOL_LIST_CMD = "uv tool list"

# Must stay shfmt-clean under the shipped .editorconfig (`space_redirects = true`: `> /dev/null`,
# never `>/dev/null`) — otherwise `configure` writes it and `quality.fix` rewrites it, forever.
# tests/integration/test_written_files_integration.py runs shfmt over the rendered script.
_STAMP_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

# Regenerated by `inv configure` — do not hand-edit. Installs the repo-tasks version this repo
# was last configured against. For CI and reproducibility archaeology only: a human working
# locally runs `inv repo-tasks.update` instead, which moves the shared *global* install forward.
# Re-running this script by habit would silently reinstall the global tool to whatever version
# *this* repo last pinned, yanking it out from under any other repo just being worked on.

command -v uv > /dev/null 2>&1 || {{
  echo "uv not found on PATH — install uv first" >&2
  exit 1
}}
{install_cmd} 'repo-tasks @ git+{repo_url}{pinned_ref}'
"""


def _remote_tags(c: Context) -> list[str]:
    """Every `vX.Y.Z` tag on the upstream repo, newest first — empty if it has none yet, which is
    what `update` falls back to the default branch for."""
    result = c.run(f"git ls-remote --tags --refs --sort=-v:refname {_REPO_URL} 'v*'", hide=True, warn=True)
    if not result.ok or not result.stdout.strip():
        return []
    return [ref.rsplit("refs/tags/", 1)[-1] for ref in result.stdout.strip().splitlines()]


def _latest_tag(c: Context) -> str | None:
    tags = _remote_tags(c)
    return tags[0] if tags else None


def _stamped_version() -> str | None:
    """The version pinned in this repo's own bootstrap-repo-tasks.sh, or None if it hasn't been
    stamped yet (run `inv configure`) or was stamped before any tag existed (unpinned form,
    nothing to compare against)."""
    if not _STAMP_PATH.exists():
        return None
    match = re.search(r"repo-tasks @ git\+[^@']+@v([^']+)'", _STAMP_PATH.read_text(encoding="utf-8"))
    return match.group(1) if match else None


@requires(NETWORK)
@task
def update(c: Context):
    """Move the global daily-driver repo-tasks uv tool install forward to the latest tagged
    release (falls back to the default branch with a warning if no release has been tagged
    yet)."""
    tag = _latest_tag(c)
    if tag:
        target = f"repo-tasks @ git+{_REPO_URL}@{tag}"
    else:
        target = f"repo-tasks @ git+{_REPO_URL}"
        print("[repo-tasks.update] no tagged release found yet — installing from the default branch")
    c.run(f"{_INSTALL_CMD} '{target}'", echo=True)


def _global_version(c: Context) -> str | None:
    """The version of the global `uv tool` install, or None when uv cannot answer.

    Read from uv rather than from this process, which is the whole point: `_installed_version` can
    only ever report the interpreter executing it, and in a repo carrying its own `repo-tasks` that
    is a different copy. None covers both "uv is not on PATH" and "repo-tasks is not installed as a
    tool" — neither is an error, since a consumer taking this package as a project dependency
    legitimately has no global install at all.
    """
    result = c.run(_TOOL_LIST_CMD, hide=True, warn=True)
    if not result.ok:
        return None
    for line in result.stdout.splitlines():
        # `uv tool list` prints `repo-tasks v0.3.0` then its executables, each indented.
        name, _, rest = line.partition(" ")
        if name == "repo-tasks" and rest.startswith("v"):
            return rest[1:].strip()
    return None


@task
def status(c: Context):
    """Report both repo-tasks versions in play, and compare against what this repo was last
    `configure`d against — drift detection, read-only.

    **Two numbers, always, because they are routinely different and only one of them used to be
    printed.** The *active* version is whatever `inv` process is executing this; the *global* one is
    the `uv tool` install. They coincide in a repo that carries no `repo-tasks` of its own, which is
    where this is usually run — and differ in this repo and in any consumer taking the package as a
    project dependency. Printing one under a name implying the other is what made a successful
    upgrade read as a failed one, 2026-09-08.

    Both readings are local and cheap. The third number an agent might want — the latest released
    tag — deliberately is not here: it needs the network, which routine tasks in this package do not
    take (see `ci.check-actions`, kept out of the gate for the same reason).
    """
    active = _installed_version("repo-tasks")
    global_version = _global_version(c)
    if global_version is None:
        where = "global uv tool: not installed, or uv unavailable"
    elif global_version == active:
        where = f"global uv tool: {global_version} (same)"
    else:
        where = f"global uv tool: {global_version} (differs)"
    print(f"[repo-tasks.status] active: {active} (this process); {where}")

    if not _STAMP_PATH.exists():
        print("[repo-tasks.status] this repo has no stamped bootstrap-repo-tasks.sh yet (run `inv configure`)")
        return
    expected = _stamped_version()
    if expected is None:
        print(
            f"[repo-tasks.status] {_STAMP_PATH} is pinned to an unpinned (default-branch) "
            "install — nothing to compare a version against"
        )
        return
    if active == expected:
        print(f"[repo-tasks.status] up to date — active {active}, repo expects {expected}")
    else:
        print(
            f"[repo-tasks.status] drift — active {active}, repo expects {expected}. "
            "Run `inv repo-tasks.update` to move the global install forward, or `inv configure` "
            "to re-pin this repo to what's currently installed."
        )


@task
def version(c: Context):
    """Print the repo-tasks version currently active (whatever `inv` process is executing this,
    typically the global daily-driver install)."""
    print(_installed_version("repo-tasks"))


@requires(NETWORK)
@task
def stamp(c: Context):
    """Regenerate bootstrap-repo-tasks.sh, pinning the repo-tasks version active right now. Runs
    as part of `inv configure` — see the generated script's own header for why a human shouldn't
    run it directly. Falls back to an unpinned install if `v{active version}` isn't an actual
    upstream tag (e.g. this checkout is ahead of the last release, or nothing's been tagged yet) —
    pinning to a tag that doesn't exist would make the generated script fail every time it runs.

    **The number is the *active* one — this process's `repo-tasks`, not the global uv tool — and
    that is deliberate.** The script records what this repo was last configured against, so a
    consumer carrying its own pinned `repo-tasks` should stamp the version its own tooling resolves
    to rather than whatever happens to be installed globally on the machine. `status` reads both and
    says so; this reads one and says which.

    It therefore says which source it used and warns when that version is behind the newest release,
    because the failure mode is silent: an editable install's recorded metadata does not move when
    `bump-my-version` edits `pyproject.toml`, so a stale reading looks like an ordinary version and
    pins consumers to a genuinely older release. This is why the task needs the network at all — the
    tag list is what makes "behind" answerable, and it was reaching for it undeclared until
    2026-09-12."""
    active = _installed_version("repo-tasks")
    tags = _remote_tags(c)
    pinned_ref = f"@v{active}" if f"v{active}" in tags else ""
    print(f"[repo-tasks.stamp] active version {active}, read from the interpreter running this task")
    if not tags:
        print(
            "[repo-tasks.stamp] the upstream tag list came back empty — nothing is tagged yet, or "
            "the remote was unreachable; stamping an unpinned install"
        )
    elif not pinned_ref:
        print(f"[repo-tasks.stamp] v{active} isn't a real upstream tag — stamping an unpinned install")
    elif tags[0] != f"v{active}":
        print(
            f"[repo-tasks.stamp] v{active} is behind the latest release {tags[0]} — pinning v{active}, "
            "since that is what this repo is configured against. `inv repo-tasks.update` then "
            "`inv configure` if you meant to move forward."
        )
    script = _STAMP_TEMPLATE.format(install_cmd=_INSTALL_CMD, repo_url=_REPO_URL, pinned_ref=pinned_ref)
    _STAMP_PATH.write_text(script, encoding="utf-8")
    _STAMP_PATH.chmod(_STAMP_PATH.stat().st_mode | 0o111)
    print(f"[repo-tasks.stamp] wrote {_STAMP_PATH}" + (f", pinned to v{active}" if pinned_ref else ""))
